### ISSUE TITLE
Simplify setting up big models

### ISSUE THREAD

**Issue by rjplevin** [mimiframework/Mimi.jl#190]
1. Instead of having to include all the components "manually", we can have a "components" directory from which all .jl files are included. I'm already doing this in the the core with a func defined in Mimi.jl `load_comps(dirname::String="./components")`.

2. `@defcomp` adds all components to a global registry. For the (presumably majority of) cases where this registry is exactly the list you want loaded, we can define something like `add_all_components(model)` which does just that. I've already added a topological sort function based on internal connection dependencies. It probably needs some refinement, but it's close. This avoids having to manually add comps in a right order. (Are there any dependency loops where we would have to indicate dependence on the prior timestep? If not we can postpone solving that.) [See also #166]

3. For data loading, we can add a little structure to the data directory so that the paths to files are `data/$(comp_name)/$(param_name).csv`. Then a common `load_all_data(model, my_validation_func)` could load and test everything as required.

**Comment by davidanthoff** [comment]
On 1) I'm not so sure. It will for example break all IDE integration because we can't traverse those kind of includes.

On 2), we can discuss that in #166, but I would put that on the backlog because we do have dependency loops everywhere and solving that properly wouldn't be trivial, and I don't think it is a big pain point or something we promised to do in this first round.

On 3, yes we should definitely make things simpler. I've thought a little bit about this in the past, and I think there are a bunch of extra design dimensions to this. Lets put that one on our list of things we need to figure out in one of our next meetings.

**Comment by davidanthoff** [comment]
We're closing this because composite components essentially address this and we have a separate issue for the parameter loading story.
