### ISSUE TITLE
Don't return interactive plots from the plot function

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#487]
Currently `explore(m, :foo, :bar)` returns interactive plots. I don't think that is ideal, I think instead we would want to return just a plain plot there.

**Comment by lrennels** [comment]
@davidanthoff I can go about changing this to a regular line plot instead of an interactive one, but just want to understand the reasoning a bit better. 

Is this not ideal because the saved version is static, and thus sort of repetitive since it shows two versions of the same image? I guess it's more a question of what the user-facing goal is for `explore` (or a new name per the other issue) of a specific variable or parameter as opposed to `explore` of a full model.  I had thought of them as very similar, and wanted to the plots to mirror each other with the additional ability to easily save, but I can see why that might not be ideal for interactive plots? On the other hand if a user wants to view a specific variable or parameter, it seemed wise to incorporate interactivity there especially for cases where the scale makes the ability to zoom in almost necessary.

**Comment by lrennels** [comment]
I guess a keyword argument is always a possibility ...

**Comment by lrennels** [comment]
Hmm this said, I think saving several of the files types like `.png` fails for interactive plots, so perhaps yes it would be best to create only static plots with `explore(m, :foo, :bar)`

**Comment by lrennels** [comment]
FYI previous conversations led to this addition to the documentation:

```
Alternatively, in order to view just one parameter or variable, call the function explore as below to return a plot object and automatically display the plot in a viewer, assuming explore is the last command executed. This call will return the type VegaLite.VLSpec, which you may interact with using the API described in the VegaLite.jl documentation. For example, VegaLite.jl plots can be saved as PNG, SVG, PDF and EPS files. You may save a plot using the save function. Note that saving an interactive plot in a non-interactive file format, such as .pdf or .svg will result in a warning WARN Can not resolve event source: window, but the plot will be saved as a static image. If you wish to preserve interactive capabilities, you may save it using the .vegalite file extension. If you then open this file in Jupyter lab, the interactive aspects will be preserved.
```

**Comment by lrennels** [comment]
handled in PR #491

**Comment by davidanthoff** [comment]
Good points. So maybe what we _really_ need is an `explore` method for an individual variable that still returns an interactive figure, and a `plot` method that returns a static plot that one can e.g. directly save and have something useful? I'm not super sure... 

The motivation for this issue was that I plotted a variable in a Jupyter Notebook, and it looks weird to have two graphs on top of each other that show the same thing.
