### ISSUE TITLE
deprecate some component functions

### ISSUE THREAD

**Issue by lrennels** [mimiframework/Mimi.jl#662]
- With our current "import" semantics, I think some funcs that take a ComponentPath arg may be deprecated. I doubt they're used by anyone yet.
- Similarly, funcs taking string paths, like "/path/to/component:datum_name" are probably deprecated.

**Comment by ckingdon95** [comment]
I think I've taken care of most of these in this PR: #687 
but we may want to do one more pass through later

**Comment by ckingdon95** [comment]
I've been going back and forth on this, I removed many of the methods that take ComponentPaths as arguments, but not all of them, since some of the internal implementation of `connect_param!` still relies on them (although they don't have to, it would just take a little bit of work to go through and change some of them). I'm sort of inclined to put this off until v1.0.1 or something, but not sure if removing them at that point would be violation/changing of the API. Might just wait for David's input on this before deciding.

**Comment by lrennels** [comment]
I think putting it off until v1.0.1 seems sensible, especially if none of the methods that use the ComponentPath are really exported for user use.

**Comment by ckingdon95** [comment]
as discussed last week, I will rename some of the `connect_param!` methods that still use `ComponentPath`s that should now only be used internally
