### ISSUE TITLE
create_external_param!

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#750]
See discussion [here](https://github.com/anthofflab/MimiFAIR.jl/pull/19#pullrequestreview-472965223).

@ckingdon95 rightly pointed out that this is less of a problem with models that are packaged as composite components. I still think, though, that there is a valid use case for this kind of pattern when folks are not using composite components. I think we should just support both cases.

Is the existing, private function `set_external_param!` essentially what we are talking about already?

I guess one question is what function name would be good in this scenario.

**Comment by ckingdon95** [comment]
yes, I think that the private `set_external_param!` function is what we are talking about. I think we will want to discuss any possible corner cases and make sure we right up a test file that has examples of when this would error etc. (what happens if you use this function, then try to call `set_param!` with the same parameter name, for example)

I think I like the name `create_external_param!` or maybe just `create_param!`

**Comment by davidanthoff** [comment]
Yes!

The error conditions I can think of right now would essentially be that whenever an external parameter already exists, and one tries to create it again, we error. So that would imply that if one calls `create_param!` twice with the same name, it errors. Given that `set_param!` internally would also call `create_param!`, calling any combination of these two that would end up creating parameters with the same name would also error, right? Beyond that I can't really think of anything right now...

Do we use the terminology of "external parameter" in the docs anywhere, or is that really a concept that we just use in the dev team? If the latter, then `create_param!` looks better to me as well. Essentially the story would simply be that `set_param!` is a shortcut for the `create_param!` & `connect_param!` combo.

**Comment by davidanthoff** [comment]
We could use `set_param!(m, :name, value, auto_connect=false)`.
